name: Stephen Daws
favicon: null
layout_spectrum: 0.26461
typography_spectrum: 0.08168267644941807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfc'
    - '#858200'
    - '#b80000'
    - '#53668c'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
